import { FormEvent, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";
import { Building2, FileCheck2, Upload, Download, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";

type Profile = { name: string; registrationNumber: string; capabilities: string[]; cpvCodes: string[]; keywords: string[]; excludedKeywords: string[] };
type Evidence = { id: string; title: string; evidenceType: string; issuer: string; validUntil?: string | null; tags: string[]; status: string; fileSize?: number; extractionMetadata?: { method?: string; pageCount?: number; warnings?: string[] } };
type Data = { profile: Profile; evidence: Evidence[] };
const joined = (items?: string[]) => items?.join(", ") || "";

export default function CompanyPage() {
  const client = useQueryClient();
  const file = useRef<HTMLInputElement>(null);
  const query = useQuery({ queryKey: ["/api/company"], queryFn: ({ signal }) => customFetch<Data>("/api/company", { signal }) });
  const refresh = () => void client.invalidateQueries({ queryKey: ["/api/company"] });
  const save = useMutation({ mutationFn: (body: Profile) => customFetch("/api/company", { method: "PUT", body: JSON.stringify(body), headers: { "Content-Type": "application/json" } }), onSuccess: () => { toast.success("Profil firme je sačuvan."); refresh(); } });
  const add = useMutation({ mutationFn: (body: FormData) => customFetch("/api/company/evidence", { method: "POST", body }), onSuccess: () => { toast.success("Dokaz je dodat za pregled."); refresh(); }, onError: (error: Error) => toast.error(error.message) });
  const update = useMutation({ mutationFn: ({ id, status }: { id: string; status: string }) => customFetch(`/api/company/evidence/${id}`, { method: "PATCH", body: JSON.stringify({ status }), headers: { "Content-Type": "application/json" } }), onSuccess: refresh });
  if (query.isLoading) return <p>Učitavanje profila firme…</p>;
  if (!query.data) return <p className="text-red-700">Profil firme nije dostupan.</p>;
  const p = query.data.profile;
  const submitProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const split = (name: string) => String(fd.get(name) || "").split(",").map(x => x.trim()).filter(Boolean); save.mutate({ name: String(fd.get("name") || ""), registrationNumber: String(fd.get("registrationNumber") || ""), capabilities: split("capabilities"), cpvCodes: split("cpvCodes"), keywords: split("keywords"), excludedKeywords: split("excludedKeywords") }); };
  const submitEvidence = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); if (!fd.get("file")) { toast.error("Izaberite dokument."); return; } add.mutate(fd); };
  const download = async (item: Evidence) => { const blob = await customFetch<Blob>(`/api/company/evidence/${item.id}/download`, { responseType: "blob" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = item.title; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <div className="max-w-6xl mx-auto space-y-6">
    <div><h1 className="text-2xl font-bold flex items-center gap-2"><Building2 className="text-primary" />Profil i dokazi firme</h1><p className="text-muted-foreground mt-1">Jednom uneseni kapaciteti i odobreni dokazi koriste se za provjerljivo povezivanje sa uslovima tendera.</p></div>
    <Card><CardHeader><CardTitle>Podaci za pretragu i podudaranje</CardTitle></CardHeader><CardContent><form key={JSON.stringify(p)} onSubmit={submitProfile} className="grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Naziv firme<Input name="name" defaultValue={p.name} className="mt-1" /></label><label className="text-sm font-medium">ID / registracijski broj<Input name="registrationNumber" defaultValue={p.registrationNumber} className="mt-1" /></label><label className="text-sm font-medium">Kapaciteti, odvojeni zarezom<Input name="capabilities" defaultValue={joined(p.capabilities)} className="mt-1" /></label><label className="text-sm font-medium">CPV kodovi<Input name="cpvCodes" defaultValue={joined(p.cpvCodes)} className="mt-1" /></label><label className="text-sm font-medium">Ključne riječi<Input name="keywords" defaultValue={joined(p.keywords)} className="mt-1" /></label><label className="text-sm font-medium">Isključene riječi<Input name="excludedKeywords" defaultValue={joined(p.excludedKeywords)} className="mt-1" /></label><div className="md:col-span-2"><Button disabled={save.isPending}>{save.isPending ? "Čuvanje…" : "Sačuvaj profil"}</Button></div></form></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Upload className="w-5 h-5" />Dodaj dokaz</CardTitle></CardHeader><CardContent><form onSubmit={submitEvidence} className="grid md:grid-cols-3 gap-4"><label className="text-sm font-medium">Naziv<Input name="title" placeholder="npr. Licenca za neživotna osiguranja" className="mt-1" /></label><label className="text-sm font-medium">Vrsta<Input name="evidenceType" placeholder="licenca, potvrda, referenca…" className="mt-1" /></label><label className="text-sm font-medium">Izdavalac<Input name="issuer" className="mt-1" /></label><label className="text-sm font-medium">Važi do<Input type="date" name="validUntil" className="mt-1" /></label><label className="text-sm font-medium">Oznake<Input name="tags" placeholder="osiguranje, odgovornost…" className="mt-1" /></label><label className="text-sm font-medium">PDF, DOCX ili TXT<Input ref={file} type="file" name="file" accept=".pdf,.docx,.txt" className="mt-1" /></label><div className="md:col-span-3"><Button disabled={add.isPending}>{add.isPending ? "Čitanje dokumenta…" : "Dodaj u biblioteku"}</Button></div></form></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><FileCheck2 className="w-5 h-5" />Biblioteka dokaza</CardTitle></CardHeader><CardContent className="space-y-3">{query.data.evidence.length === 0 ? <p className="text-sm text-muted-foreground">Još nema dokaza. Dodajte licence, potvrde, reference i druge priloge koji se ponavljaju kroz tendere.</p> : query.data.evidence.map(item => <div key={item.id} className="border rounded-lg p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{item.title}</p><span className={`text-xs rounded-full px-2 py-0.5 ${item.status === "approved" ? "bg-green-100 text-green-800" : item.status === "expired" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}`}>{item.status === "approved" ? "odobren" : item.status === "expired" ? "istekao" : "nacrt"}</span></div><p className="text-xs text-muted-foreground mt-1">{item.evidenceType} · {item.issuer || "izdavalac nije unesen"} · {item.validUntil ? `važi do ${new Date(item.validUntil).toLocaleDateString("bs-BA")}` : "rok nije unesen"} · {item.extractionMetadata?.method || "metoda čitanja nije zabilježena"}</p>{!!item.extractionMetadata?.warnings?.length && <p className="text-xs text-amber-700 mt-1 flex gap-1"><AlertTriangle className="w-3.5 h-3.5" />{item.extractionMetadata.warnings.join(" ")}</p>}</div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => update.mutate({ id: item.id, status: item.status === "approved" ? "draft" : "approved" })}>{item.status === "approved" ? "Vrati u nacrt" : "Odobri dokaz"}</Button><Button variant="ghost" size="sm" onClick={() => void download(item)}><Download className="w-4 h-4" /></Button></div></div>)}</CardContent></Card>
  </div>;
}
