import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";
import { BellRing, CheckCircle2, Plus, Search, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Link } from "wouter";
import { formatMoney, formatDate } from "@/lib/format";

type Market = { id: string; name: string; cpvCodes: string[]; keywords: string[]; authorityNames: string[]; minValue?: number | null; maxValue?: number | null; openOnly: boolean };
type Tender = { id: string; externalId: string; title: string; contractingAuth: string; estimatedValue?: number | null; currency: string; publicationDate: string; deadline?: string | null; status: string; reasons: string[] };
type Results = { market: Market; tenders: Tender[]; checkedAt: string };
const joined = (values?: string[]) => values?.join(", ") || "";
const input = "mt-1 h-9";

export default function MarketsPage() {
  const client = useQueryClient();
  const [selected, setSelected] = useState<string | null>(null);
  const markets = useQuery({ queryKey: ["markets"], queryFn: ({ signal }) => customFetch<Market[]>("/api/markets", { signal }) });
  const result = useQuery({ queryKey: ["market-tenders", selected], enabled: !!selected, queryFn: ({ signal }) => customFetch<Results>(`/api/markets/${selected}/tenders`, { signal }) });
  const save = useMutation({ mutationFn: ({ id, body }: { id?: string; body: Record<string, unknown> }) => customFetch<Market>(id ? `/api/markets/${id}` : "/api/markets", { method: id ? "PUT" : "POST", body: JSON.stringify(body), headers: { "Content-Type": "application/json" } }), onSuccess: data => { void client.invalidateQueries({ queryKey: ["markets"] }); setSelected(data.id); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); const split = (name: string) => String(fd.get(name) || "").split(",").map(value => value.trim()).filter(Boolean); save.mutate({ id: active?.id, body: { name: fd.get("name"), cpvCodes: split("cpvCodes"), keywords: split("keywords"), authorityNames: split("authorityNames"), minValue: fd.get("minValue"), maxValue: fd.get("maxValue"), openOnly: fd.get("openOnly") === "on" } }); };
  const active = markets.data?.find(item => item.id === selected);
  return <div className="max-w-7xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold flex gap-2 items-center"><SlidersHorizontal className="text-primary" />Moja tržišta</h1><p className="text-sm text-muted-foreground mt-1">Sačuvajte CPV kodove, ključne riječi, kupce i vrijednosni raspon. Dnevni red prikazuje samo tendere koji odgovaraju tom tržištu.</p></div>
    <div className="grid lg:grid-cols-[320px_1fr] gap-6"><Card><CardHeader><CardTitle className="text-base flex items-center justify-between">Sačuvana tržišta<Button type="button" variant="ghost" size="sm" onClick={() => setSelected(null)}>Novo</Button></CardTitle></CardHeader><CardContent className="space-y-2">{markets.isLoading ? <p className="text-sm">Učitavanje…</p> : markets.data?.length ? markets.data.map(market => <button key={market.id} onClick={() => setSelected(market.id)} className={`text-left rounded-lg border p-3 w-full ${selected === market.id ? "border-primary bg-primary/5" : "hover:bg-muted/60"}`}><strong className="text-sm">{market.name}</strong><p className="text-xs text-muted-foreground mt-1">{market.cpvCodes.length} CPV · {market.keywords.length} pojmova · {market.openOnly ? "samo otvorene" : "svi statusi"}</p></button>) : <p className="text-sm text-muted-foreground">Kreirajte prvo tržište, npr. „Osiguranje vozila“.</p>}</CardContent></Card>
      <div className="space-y-6"><Card><CardHeader><CardTitle className="text-base flex gap-2"><Plus className="w-5 h-5" />{active ? "Uredi tržište" : "Novo tržište"}</CardTitle></CardHeader><CardContent><form key={active?.id || "new"} onSubmit={submit} className="grid md:grid-cols-2 gap-3"><label className="text-sm font-medium">Naziv<Input className={input} name="name" placeholder="npr. Osiguranje vozila" defaultValue={active?.name || ""} /></label><label className="text-sm font-medium">CPV kodovi<Input className={input} name="cpvCodes" placeholder="66514110-0, 66510000-8" defaultValue={joined(active?.cpvCodes)} /></label><label className="text-sm font-medium">Ključne riječi<Input className={input} name="keywords" placeholder="kasko, vozila, polisa" defaultValue={joined(active?.keywords)} /></label><label className="text-sm font-medium">Kupci / organi<Input className={input} name="authorityNames" placeholder="Vodovod, Grad Tuzla" defaultValue={joined(active?.authorityNames)} /></label><label className="text-sm font-medium">Min. vrijednost (KM)<Input className={input} name="minValue" type="number" defaultValue={active?.minValue ?? ""} /></label><label className="text-sm font-medium">Maks. vrijednost (KM)<Input className={input} name="maxValue" type="number" defaultValue={active?.maxValue ?? ""} /></label><label className="md:col-span-2 flex gap-2 text-sm items-center"><input name="openOnly" type="checkbox" defaultChecked={active?.openOnly ?? true} />Samo otvoreni tenderi</label><div className="md:col-span-2"><Button disabled={save.isPending}>{save.isPending ? "Čuvanje…" : active ? "Ažuriraj tržište" : "Sačuvaj tržište"}</Button></div></form></CardContent></Card>
        {selected && <Card><CardHeader><CardTitle className="text-base flex justify-between gap-2"><span className="flex gap-2"><Search className="w-5 h-5" />Dnevni red tržišta</span><span className="text-xs font-normal text-muted-foreground">{result.data ? `${result.data.tenders.length} rezultata · provjereno ${new Date(result.data.checkedAt).toLocaleString("bs-BA")}` : ""}</span></CardTitle></CardHeader><CardContent>{result.isLoading ? <p>Tražim podudaranja…</p> : result.data?.tenders.length ? <div className="space-y-3">{result.data.tenders.map(tender => <Link key={tender.id} href={`/tenders/${tender.id}`}><div className="border rounded-lg p-4 hover:border-primary hover:bg-primary/5"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-medium text-sm">{tender.title}</p><p className="text-xs text-muted-foreground mt-1">{tender.contractingAuth} · {tender.externalId} · objavljeno {formatDate(tender.publicationDate)}</p></div><div className="text-right text-sm"><strong>{formatMoney(tender.estimatedValue, tender.currency)}</strong><p className="text-xs text-muted-foreground">rok {formatDate(tender.deadline)}</p></div></div>{tender.reasons.length > 0 && <p className="text-xs text-primary mt-2 flex gap-1"><CheckCircle2 className="w-3.5 h-3.5" />Podudaranje: {tender.reasons.join(", ")}</p>}</div></Link>)}</div> : <p className="text-sm text-muted-foreground">Nema otvorenih podudaranja u trenutno preuzetim tenderima.</p>}</CardContent></Card>}</div></div></div>;
}
