import { db } from "@workspace/db";
import { historicalAwardsTable, urzDecisionsTable } from "@workspace/db";
import { logger } from "../lib/logger";
import { nanoid } from "../lib/nanoid";

export async function seedHistoryData() {
  try {
    const existingAwards = await db.select().from(historicalAwardsTable).limit(1);
    if (existingAwards.length === 0) {
      logger.info("Seeding historical awards for Insurance and Technical Inspection...");

      const awards = [
        {
          id: nanoid(),
          contractingAuth: "JP Elektroprivreda BiH d.d. Sarajevo",
          procedureName: "Usluge kasko i AO osiguranja voznog parka EPBiH 2024",
          winnerName: "Sarajevo Osiguranje d.d.",
          winningBidAmount: 498000,
          estimatedValue: 600000,
          discountPct: 17.0,
          currency: "KM",
          awardDate: new Date("2024-11-15"),
          competitorOffersCount: 4,
          cpvKod: "66514110-0",
          ejnBroj: "1405-1-2-45-3-112/24",
        },
        {
          id: nanoid(),
          contractingAuth: "JP Elektroprivreda BiH d.d. Sarajevo",
          procedureName: "Usluge osiguranja voznog parka i postrojenja EPBiH 2025",
          winnerName: "Euroherc osiguranje d.d.",
          winningBidAmount: 512000,
          estimatedValue: 620000,
          discountPct: 17.4,
          currency: "KM",
          awardDate: new Date("2025-11-20"),
          competitorOffersCount: 3,
          cpvKod: "66514110-0",
          ejnBroj: "1405-1-2-78-3-210/25",
        },
        {
          id: nanoid(),
          contractingAuth: "BH Telecom d.d. Sarajevo",
          procedureName: "Osiguranje imovine, objekata i data centara BH Telecoma 2025",
          winnerName: "Sarajevo Osiguranje d.d.",
          winningBidAmount: 1150000,
          estimatedValue: 1350000,
          discountPct: 14.8,
          currency: "KM",
          awardDate: new Date("2025-05-10"),
          competitorOffersCount: 5,
          cpvKod: "66515200-5",
          ejnBroj: "1424-1-2-110-3-85/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Klinički centar Univerziteta u Sarajevu (KCUS)",
          procedureName: "Kolektivno osiguranje zdravstvenih radnika KCUS od nezgode 2025",
          winnerName: "Triglav Osiguranje d.d.",
          winningBidAmount: 285000,
          estimatedValue: 335000,
          discountPct: 14.9,
          currency: "KM",
          awardDate: new Date("2025-06-01"),
          competitorOffersCount: 4,
          cpvKod: "66512100-3",
          ejnBroj: "260-1-2-32-3-44/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Grad Mostar",
          procedureName: "Usluge osiguranja imovine i lica Grada Mostara 2025",
          winnerName: "Croatia osiguranje d.d.",
          winningBidAmount: 198000,
          estimatedValue: 230000,
          discountPct: 13.9,
          currency: "KM",
          awardDate: new Date("2025-09-08"),
          competitorOffersCount: 3,
          cpvKod: "66515000-3",
          ejnBroj: "123-1-2-55-3-67/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Agencija za rad i zapošljavanje BiH",
          procedureName: "Grupno životno i osiguranje zaposlenika od nezgode 2024",
          winnerName: "Triglav Osiguranje d.d.",
          winningBidAmount: 122000,
          estimatedValue: 140000,
          discountPct: 12.8,
          currency: "KM",
          awardDate: new Date("2024-12-15"),
          competitorOffersCount: 2,
          cpvKod: "66511000-5",
          ejnBroj: "719-1-2-12-3-20/24",
        },
        {
          id: nanoid(),
          contractingAuth: "Vlada Federacije BiH",
          procedureName: "Kasko i AO osiguranje službenih vozila Vlade FBiH 2025",
          winnerName: "ASA Central Osiguranje d.d.",
          winningBidAmount: 78000,
          estimatedValue: 92000,
          discountPct: 15.2,
          currency: "KM",
          awardDate: new Date("2025-08-12"),
          competitorOffersCount: 5,
          cpvKod: "66514110-0",
          ejnBroj: "405-1-2-19-3-33/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Autoceste FBiH d.o.o. Mostar",
          procedureName: "Osiguranje objekata naplate cestarine i radnika Autocesta",
          winnerName: "ASA Central Osiguranje d.d.",
          winningBidAmount: 142000,
          estimatedValue: 165000,
          discountPct: 13.9,
          currency: "KM",
          awardDate: new Date("2025-10-18"),
          competitorOffersCount: 4,
          cpvKod: "66515000-3",
          ejnBroj: "258-1-2-65-3-92/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Univerzitet u Sarajevu",
          procedureName: "Osiguranje motornih vozila i pratnje Univerziteta 2025",
          winnerName: "Sarajevo Osiguranje d.d.",
          winningBidAmount: 285000,
          estimatedValue: 330000,
          discountPct: 13.6,
          currency: "KM",
          awardDate: new Date("2025-03-20"),
          competitorOffersCount: 4,
          cpvKod: "66514110-0",
          ejnBroj: "1350-1-2-88-3-104/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Opća bolnica Prim. dr. Abdulah Nakaš",
          procedureName: "Osiguranje imovine, lica i voznog parka OB Sarajevo 2025",
          winnerName: "Euroherc osiguranje d.d.",
          winningBidAmount: 425000,
          estimatedValue: 500000,
          discountPct: 15.0,
          currency: "KM",
          awardDate: new Date("2025-04-15"),
          competitorOffersCount: 5,
          cpvKod: "66515000-3",
          ejnBroj: "986-1-2-41-3-77/25",
        },
        {
          id: nanoid(),
          contractingAuth: "JP Željeznice FBiH d.o.o. Sarajevo",
          procedureName: "Osiguranje lokomotiva, kompozicija i tereta u željezničkom saobraćaju",
          winnerName: "Wiener Osiguranje VIG",
          winningBidAmount: 235000,
          estimatedValue: 280000,
          discountPct: 16.1,
          currency: "KM",
          awardDate: new Date("2025-07-04"),
          competitorOffersCount: 3,
          cpvKod: "66514110-0",
          ejnBroj: "1055-1-2-62-3-94/25",
        },
        {
          id: nanoid(),
          contractingAuth: "RMU Banovići d.d.",
          procedureName: "Obavezno osiguranje rudarskih mašina i transportnih vozila",
          winnerName: "Sarajevo Osiguranje d.d.",
          winningBidAmount: 119000,
          estimatedValue: 145000,
          discountPct: 17.9,
          currency: "KM",
          awardDate: new Date("2025-08-29"),
          competitorOffersCount: 4,
          cpvKod: "66514110-0",
          ejnBroj: "820-1-2-29-3-51/25",
        },
        // --- TEHNIČKI PREGLEDI VOZILA ---
        {
          id: nanoid(),
          contractingAuth: "Ministarstvo unutrašnjih poslova Kantona Sarajevo (MUP KS)",
          procedureName: "Redovni i preventivni tehnički pregledi službenih patrolnih vozila i motocikala 2025",
          winnerName: "ASA Central STP d.o.o. Sarajevo",
          winningBidAmount: 64500,
          estimatedValue: 75000,
          discountPct: 14.0,
          currency: "KM",
          awardDate: new Date("2025-07-22"),
          competitorOffersCount: 4,
          cpvKod: "71631200-2",
          ejnBroj: "618-1-2-33-3-58/25",
        },
        {
          id: nanoid(),
          contractingAuth: "KJKP RAD d.o.o. Sarajevo",
          procedureName: "Usluge tehničkog pregleda teretnih i specijalnih komunalnih vozila",
          winnerName: "Remontmontaža STP d.o.o.",
          winningBidAmount: 74000,
          estimatedValue: 88000,
          discountPct: 15.9,
          currency: "KM",
          awardDate: new Date("2025-05-30"),
          competitorOffersCount: 3,
          cpvKod: "71631200-2",
          ejnBroj: "432-1-2-89-3-115/25",
        },
        {
          id: nanoid(),
          contractingAuth: "KJKP GRAS d.o.o. Sarajevo",
          procedureName: "Ispitivanje autobusa, tehnički pregled i baždarenje tahografa",
          winnerName: "Centrotrans STP d.d. Sarajevo",
          winningBidAmount: 98000,
          estimatedValue: 115000,
          discountPct: 14.8,
          currency: "KM",
          awardDate: new Date("2025-08-14"),
          competitorOffersCount: 3,
          cpvKod: "71631200-2",
          ejnBroj: "870-1-2-47-3-81/25",
        },
        {
          id: nanoid(),
          contractingAuth: "JU Zavod za hitnu medicinsku pomoć KS",
          procedureName: "Usluge tehničkih pregleda sanitetskih i hitnih vozila za 2025. godinu",
          winnerName: "ASA Central STP d.o.o. Sarajevo",
          winningBidAmount: 32000,
          estimatedValue: 38000,
          discountPct: 15.8,
          currency: "KM",
          awardDate: new Date("2025-09-02"),
          competitorOffersCount: 3,
          cpvKod: "71631200-2",
          ejnBroj: "540-1-2-21-3-39/25",
        },
        {
          id: nanoid(),
          contractingAuth: "Federalna uprava civilne zaštite (FUCZ)",
          procedureName: "Tehnički pregled deminerskih i terenskih vozila 4x4",
          winnerName: "Cromex STP d.o.o.",
          winningBidAmount: 41000,
          estimatedValue: 48000,
          discountPct: 14.6,
          currency: "KM",
          awardDate: new Date("2025-06-18"),
          competitorOffersCount: 3,
          cpvKod: "71631200-2",
          ejnBroj: "312-1-2-15-3-28/25",
        }
      ];

      for (const a of awards) {
        await db.insert(historicalAwardsTable).values(a);
      }
      logger.info("Historical competitor awards data seeded successfully!");
    }

    // Seed URŽ decisions if empty
    const existingUrz = await db.select().from(urzDecisionsTable).limit(1);
    if (existingUrz.length === 0) {
      logger.info("Seeding URŽ legal precedent decisions...");

      const decisions = [
        {
          id: nanoid(),
          caseNumber: "UP2-01-07.1-1422/24",
          contractingAuth: "JP Elektroprivreda BiH d.d. Sarajevo",
          procedureName: "Nabavka usluga kasko i autoodgovornosti (AO) za teretna i putnička motorna vozila",
          appellant: "ASA Central Osiguranje d.d.",
          outcome: "USVOJENA_PONISTENJE",
          outcomeLabel: "Usvojena žalba — Poništen postupak nabavke",
          legalBasis: "Član 54. stav (1) Zakona o javnim nabavkama BiH",
          sporniUslov: "Zahtjev da ponuđač posjeduje ovlašteni servis ili ugovor o poslovnoj saradnji sa servisom na udaljenosti do najviše 5 km od zgrade direkcije naručioca.",
          summary: "URŽ je utvrdio da je uslov teritorijalnog ograničenja od 5 km nezakonit i diskriminatoran, jer neopravdano sužava konkurenciju i favorizuje lokalnog ponuđača. Naručilac nije dokazao tehničku nužnost takvog ograničenja.",
          category: "Osiguranje",
          decisionDate: new Date("2024-10-14"),
          ejnBroj: "1405-1-2-45-3-112/24",
        },
        {
          id: nanoid(),
          caseNumber: "UP2-01-07.1-918/24",
          contractingAuth: "Ministarstvo unutrašnjih poslova Kantona Sarajevo (MUP KS)",
          procedureName: "Redovni i preventivni tehnički pregledi službenih vozila i motocikala",
          appellant: "Sarajevo Osiguranje d.d.",
          outcome: "USVOJENA_IZMJENA_TD",
          outcomeLabel: "Djelimično usvojena žalba — Naložena izmjena tenderske dokumentacije",
          legalBasis: "Član 61. stav (2) Zakona o javnim nabavkama BiH",
          sporniUslov: "Zahtjev za bankarskom garancijom za ozbiljnost ponude u iznosu od 5% bez adekvatnog obrazloženja rizika.",
          summary: "Naloženo je naručiocu da izmijeni sporni član TD i uskladi garanciju sa zakonskim okvirom do maksimalno 2% procijenjene vrijednosti nabavke, te da produži rok za predaju ponuda za 15 dana.",
          category: "Tehnički pregled",
          decisionDate: new Date("2024-07-28"),
          ejnBroj: "618-1-2-33-3-58/24",
        },
        {
          id: nanoid(),
          caseNumber: "UP2-01-07.1-1780/23",
          contractingAuth: "KJKP GRAS d.o.o. Sarajevo",
          procedureName: "Ispitivanje autobusa, tehnički pregled i baždarenje tahografa",
          appellant: "ASA Central STP d.o.o. Sarajevo",
          outcome: "USVOJENA_IZMJENA_TD",
          outcomeLabel: "Usvojena žalba — Naložena izmjena tehničke specifikacije",
          legalBasis: "Član 54. stav (2) i (3) ZJN BiH (Zabrana navođenja brendova i specifičnih proizvođača)",
          sporniUslov: "U tehničkoj specifikaciji zahtijevano posjedovanje mjerne opreme isključivo proizvođača 'Maha' ili 'VDO' bez dodatka riječi 'ili ekvivalent'.",
          summary: "URŽ je usvojio žalbu i naložio ugovornom organu da u specifikaciju unese odrednicu 'ili ekvivalent' sa objektivnim parametrima funkcionalnosti.",
          category: "Tehnički pregled",
          decisionDate: new Date("2023-11-19"),
          ejnBroj: "870-1-2-47-3-81/23",
        },
        {
          id: nanoid(),
          caseNumber: "UP2-01-07.1-605/24",
          contractingAuth: "Vlada Federacije BiH",
          procedureName: "Kasko i AO osiguranje službenih motornih vozila",
          appellant: "Triglav Osiguranje d.d.",
          outcome: "ODBIJENA",
          outcomeLabel: "Odbijena žalba kao neosnovana",
          legalBasis: "Član 72. stav (1) Zakona o javnim nabavkama BiH",
          sporniUslov: "Zahtjev da ponuđač izda i dostavi originalne police osiguranja u roku od 3 radna dana od potpisa ugovora.",
          summary: "URŽ je ocijenio da rok od 3 radna dana za izdavanje polica nakon zaključenja ugovora ne predstavlja prekomjeran teret za licencirano osiguravajuće društvo, imajući u vidu prirodu i hitnost pokrića voznog parka.",
          category: "Osiguranje",
          decisionDate: new Date("2024-05-12"),
          ejnBroj: "405-1-2-19-3-33/24",
        },
        {
          id: nanoid(),
          caseNumber: "UP2-01-07.1-2104/23",
          contractingAuth: "BH Telecom d.d. Sarajevo",
          procedureName: "Osiguranje imovine, telekomunikacione opreme i optičke mreže",
          appellant: "Croatia osiguranje d.d.",
          outcome: "USVOJENA_PONISTENJE",
          outcomeLabel: "Usvojena žalba — Poništena odluka o izboru najpovoljnijeg ponuđača",
          legalBasis: "Član 66. Zakona o javnim nabavkama BiH (Neprirodno niska cijena)",
          sporniUslov: "Ugovorni organ nije tražio obrazloženje neprirodno niske premije koja je bila 45% ispod prosjeka ostalih ponuđača.",
          summary: "Poništena je odluka o izboru i postupak vraćen u fazu ponovne evaluacije ponuda, uz nalog da se zatraži detaljno pismeno obrazloženje kalkulacije premije i stope reosiguranja.",
          category: "Osiguranje",
          decisionDate: new Date("2023-12-05"),
          ejnBroj: "1424-1-2-110-3-85/23",
        }
      ];

      for (const d of decisions) {
        await db.insert(urzDecisionsTable).values(d);
      }
      logger.info("URŽ precedent decisions seeded successfully!");
    }
  } catch (err) {
    logger.error({ err }, "Error in seedHistoryData");
  }
}
